FROM alpine:latest

RUN apk add --no-cache protobuf-dev protoc make

# Install Go
RUN apk add --no-cache go git
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH

# Install protoc plugins for Go
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /proto

# Copy the proto files into the container

COPY . .

ENTRYPOINT ["protoc"]
