[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
pingora = "0.1"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
log = "0.4"
env_logger = "0.10"

[dev-dependencies]
cargo-watch = "8.0"
