export enum QueryKeysEnum {
  SEARCH_USERS_LIST = 'SEARCH_USERS_LIST',
  USER = 'USER',
  USER_LIST = 'USER_LIST',
  CHAT_ROOM = 'CHAT_ROOM',
  CHAT_ROOMS = 'CHAT_ROOMS',
  MESSAGES = 'MESSAGES',
  MESSAGE = 'MESSAGE',
  MESSAGE_LIST = 'MESSAGE_LIST',
  USER_CHAT_ROOMS = 'USER_CHAT_ROOMS',
}
